apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  ports:
  - name: http-main
    port: 80
    targetPort: 3000
  - name: http-dev
    port: 3003
    targetPort: 3003
  selector:
    app: nginx
